<<<<<<< HEAD
---
title: Test config
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  product:
    title: Product
    output: true
  uploads:
    title: Uploads
    output: true
key: value
>>>>>>> 3e604409c50bd77a878e07befaca45090b959edd
